name: smartpath-streamlit
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - streamlit
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - pip
  - hdbscan
  - pip:
      - seaborn  # if you ever use it
      # (add any pip-only packages here)